baseURL = "https://eloypgz.org/"
languageCode = "en-us"
title = "zer1t0"


[permalinks]
    post = "/post/:year/:month/:day/:slug/"

[[menu.main]]
    name = "Posts"
    url = "/posts/"
    weight = 1

[[menu.main]]
    name = "Projects"
    url = "/projects/"
    weight = 1

[[menu.main]]
    name = "challenges"
    url = "/challenges"
    weight = 2

[[menu.main]]
    name = "utils"
    url = "/utils"
    weight = 3

[[menu.main]]
    name = "About"
    url = "/about/"
    weight = 4
