baseURL = "https://zer1t0.gitlab.io/1_t0_zero"
languageCode = "en-us"
title = "1 t0 Zero"


[permalinks]
    post = "/post/:year/:month/:day/:slug/"

[[menu.main]]
    name = "Posts"
    url = "/posts/"
    weight = 1

[[menu.main]]
    name = "Projects"
    url = "/projects/"
    weight = 1

[[menu.main]]
    name = "About"
    url = "/about/"
    weight = 3
